### ISSUE TITLE
Query on effect of connlimit on Control plane topology and data plane topology

### ISSUE THREAD

**Issue by megarajan** [rajch/weave#10]
If we have n nodes , and have connlimit to default of 100 , 

does it mean control plane topology will have n^2 connections ie a full mesh  but data plane topology will have only 100 connections, ie a partial mesh . ? 

will increasing connlimit to n^2 , does it mean we move from partial mesh to full mesh in data plane as well ?

**Comment by rajch** [comment]
This question is better addressed to the [weaveworks mesh project](https://github.com/weaveworks/mesh), which is what the weave net router uses. I believe the limit applies to both planes.

**Comment by megarajan** [comment]
ok thanks .
