### ISSUE TITLE
seeing issue in weave ipam after upgrading kernel packages 

### ISSUE THREAD

**Issue by megarajan** [rajch/weave#11]
hi,

we are using weave 2.8.1 .

We upgraded linux packages in our ubuntu vms ("Ubuntu 20.04.6 LTS) from From 5.4.0-187-generic  to linux-image-5.4.0-190-generic and then we see the below error.

any clues on where we can look into to triage and fix the below error ?

INFO: 2024/07/31 12:54:57.657959 [allocator]: Allocate request for bf3f246f18b9b8a415251c0e46cddc24891adae104431fbcd436b8e461e2e7d2 cancelled
WARN: 2024/07/31 12:54:58.437172 Error intercepting response: for "net:default": invalid CIDR address: cancelled
INFO: 2024/07/31 12:55:14.840112 Creating container with WEAVE_CIDR ""
INFO: 2024/07/31 12:55:16.531743 Attaching container 2c75b6758a19433d08ed2b4c04662f78a52b2040ea3ab86e36f3d86d258437ed with WEAVE_CIDR "" to weave network
INFO: 2024/07/31 12:56:15.663149 [allocator]: Allocate request for 2c75b6758a19433d08ed2b4c04662f78a52b2040ea3ab86e36f3d86d258437ed cancelled
WARN: 2024/07/31 12:56:16.492068 Error intercepting response: for "net:default": invalid CIDR address: cancelled
INFO: 2024/07/31 12:56:23.960781 Attaching container 2c75b6758a19433d08ed2b4c04662f78a52b2040ea3ab86e36f3d86d258437ed with WEAVE_CIDR "" to weave network

Could you please share any clues on where to start looking ?

**Comment by megarajan** [comment]
Because of this issue , all weave connections are in "sleeve" mode only and not moving to "fastdp" mode.

**Comment by megarajan** [comment]
After enabling debugs and launching weave in debug I see these messages


INFO: 2024/08/01 05:35:26.962459 [allocator fa:e5:26:56:81:20] No valid persisted data
INFO: 2024/08/01 05:35:27.001192 [allocator fa:e5:26:56:81:20] Initialising via deferred consensus
INFO: 2024/08/01 05:35:27.025688 Listening for DNS queries on 172.17.0.1:53
INFO: 2024/08/01 05:35:27.095244 Sniffing traffic on datapath (via ODP)
INFO: 2024/08/01 05:35:27.096718 ->[192.168.31.61:6783] attempting connection
INFO: 2024/08/01 05:35:27.099495 ->[192.168.31.61:6783|26:86:8d:31:03:52(site1-dra-master0)]: connection ready; using protocol version 2
INFO: 2024/08/01 05:35:27.100313 overlay_switch ->[26:86:8d:31:03:52(site1-dra-master0)] using fastdp
INFO: 2024/08/01 05:35:27.100382 ->[192.168.31.61:6783|26:86:8d:31:03:52(site1-dra-master0)]: connection added (new peer)
INFO: 2024/08/01 05:35:27.100443 Setting up IPsec between fa:e5:26:56:81:20(site1-dra-worker2) and 26:86:8d:31:03:52(site1-dra-master0)
INFO: 2024/08/01 05:35:27.101400 ipsec: InitSALocal: 192.168.31.61 -> 192.168.31.67 :6784 0x2643b41f
INFO: 2024/08/01 05:35:27.113669 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2024/08/01 05:35:27.115548 Listening for status+metrics requests on 127.0.0.1:6782
INFO: 2024/08/01 05:35:27.115646 Waiting for Weave API Server...
DEBU: 2024/08/01 05:35:27.116411 [http] GET /status
INFO: 2024/08/01 05:35:27.117770 Finished waiting for Weave API Server
INFO: 2024/08/01 05:35:27.117958 Listening on /run/docker/plugins/weave.sock for global scope
INFO: 2024/08/01 05:35:27.118149 Listening on /run/docker/plugins/weavemesh.sock for local scope
INFO: 2024/08/01 05:35:27.118194 Creating default "weave" network
DEBU: 2024/08/01 05:35:27.119917 fastdp ->[192.168.31.61:6784|26:86:8d:31:03:52(site1-dra-master0)]: confirmed
INFO: 2024/08/01 05:35:27.121005 [ipam] RequestPool weavelocal 10.32.0.0/12  map[]
DEBU: 2024/08/01 05:35:27.121034 sleeve ->[192.168.31.61:6783|26:86:8d:31:03:52(site1-dra-master0)]: Confirm
DEBU: 2024/08/01 05:35:27.121075 [ipam] RequestPool result weave-10.32.0.0/12-10.32.0.0/12 10.32.0.0/12 map[com.docker.network.gateway:10.32.0.0/12]
DEBU: 2024/08/01 05:35:27.122025 [net] CreateNetwork &{NetworkID:9f2064805be996dee030575ef36f308491522361ff9be7d1bc6e5e1e75747718 Options:map[com.docker.network.enable_ipv6:false com.docker.network.generic:map[works.weave.multicast:true]] IPv4Data:[{AddressSpace:weavelocal Pool:10.32.0.0/12 Gateway:10.32.0.0/12 AuxAddresses:map[]}] IPv6Data:[]}
INFO: 2024/08/01 05:35:27.122072 [net] CreateNetwork 9f2064805be996dee030575ef36f308491522361ff9be7d1bc6e5e1e75747718
DEBU: 2024/08/01 05:35:27.123209 sleeve ->[192.168.31.61:6783|26:86:8d:31:03:52(site1-dra-master0)]: confirmed
DEBU: 2024/08/01 05:35:27.123251 sleeve ->[192.168.31.61:6783|26:86:8d:31:03:52(site1-dra-master0)]: sendHeartbeat
DEBU: 2024/08/01 05:35:27.127112 sleeve ->[192.168.31.61:6783|26:86:8d:31:03:52(site1-dra-master0)]: handleHeartbeat
DEBU: 2024/08/01 05:35:27.198492 [http] GET /status
DEBU: 2024/08/01 05:35:27.200507 InvalidateRoutes
DEBU: 2024/08/01 05:35:27.201523 [allocator fa:e5:26:56:81:20]: Allocator.OnGossip: 954 bytes
DEBU: 2024/08/01 05:35:27.288139 [ring fa:e5:26:56:81:20]: ReportFree token=10.42.0.0 peer=fa:e5:26:56:81:20 version=30
INFO: 2024/08/01 05:35:27.288898 ->[192.168.31.62:6783] attempting connection
INFO: 2024/08/01 05:35:27.289098 ->[192.168.31.63:6783] attempting connection
INFO: 2024/08/01 05:35:27.289194 ->[192.168.31.64:6783] attempting connection
INFO: 2024/08/01 05:35:27.289343 ->[192.168.31.66:6783] attempting connection
INFO: 2024/08/01 05:35:27.289505 ->[192.168.31.65:6783] attempting connection
INFO: 2024/08/01 05:35:27.291024 ->[192.168.31.62:6783|ee:24:a9:e7:50:0e(site1-dra-control0)]: connection ready; using protocol version 2
INFO: 2024/08/01 05:35:27.291195 overlay_switch ->[ee:24:a9:e7:50:0e(site1-dra-control0)] using fastdp
INFO: 2024/08/01 05:35:27.291341 ->[192.168.31.62:6783|ee:24:a9:e7:50:0e(site1-dra-control0)]: connection added (new peer)
INFO: 2024/08/01 05:35:27.291400 Setting up IPsec between fa:e5:26:56:81:20(site1-dra-worker2) and ee:24:a9:e7:50:0e(site1-dra-control0)
INFO: 2024/08/01 05:35:27.291574 ipsec: InitSALocal: 192.168.31.62 -> 192.168.31.67 :6784 0x80fa2dc8
INFO: 2024/08/01 05:35:27.292008 ->[192.168.31.63:6783|76:a6:72:91:2a:47(site1-dra-control1)]: connection ready; using protocol version 2
INFO: 2024/08/01 05:35:27.292173 overlay_switch ->[76:a6:72:91:2a:47(site1-dra-control1)] using fastdp
INFO: 2024/08/01 05:35:27.292235 ->[192.168.31.63:6783|76:a6:72:91:2a:47(site1-dra-control1)]: connection added (new peer)
INFO: 2024/08/01 05:35:27.292271 Setting up IPsec between fa:e5:26:56:81:20(site1-dra-worker2) and 76:a6:72:91:2a:47(site1-dra-control1)
INFO: 2024/08/01 05:35:27.294236 ->[192.168.31.64:6783|aa:e0:01:9b:27:4e(site1-dra-director1)]: connection ready; using protocol version 2
INFO: 2024/08/01 05:35:27.294350 ->[192.168.31.66:6783|e6:53:1c:64:cf:41(site1-dra-worker1)]: connection ready; using protocol version 2
INFO: 2024/08/01 05:35:27.294464 overlay_switch ->[aa:e0:01:9b:27:4e(site1-dra-director1)] using fastdp
INFO: 2024/08/01 05:35:27.294579 ->[192.168.31.64:6783|aa:e0:01:9b:27:4e(site1-dra-director1)]: connection added (new peer)
INFO: 2024/08/01 05:35:27.294694 Setting up IPsec between fa:e5:26:56:81:20(site1-dra-worker2) and aa:e0:01:9b:27:4e(site1-dra-director1)
INFO: 2024/08/01 05:35:27.294732 ->[192.168.31.65:6783|56:61:58:e3:9d:0d(site1-dra-director2)]: connection ready; using protocol version 2
INFO: 2024/08/01 05:35:27.294947 overlay_switch ->[56:61:58:e3:9d:0d(site1-dra-director2)] using fastdp
INFO: 2024/08/01 05:35:27.295030 ->[192.168.31.65:6783|56:61:58:e3:9d:0d(site1-dra-director2)]: connection added (new peer)
INFO: 2024/08/01 05:35:27.295110 Setting up IPsec between fa:e5:26:56:81:20(site1-dra-worker2) and 56:61:58:e3:9d:0d(site1-dra-director2)
INFO: 2024/08/01 05:35:27.295919 overlay_switch ->[e6:53:1c:64:cf:41(site1-dra-worker1)] using fastdp
INFO: 2024/08/01 05:35:27.295951 ->[192.168.31.66:6783|e6:53:1c:64:cf:41(site1-dra-worker1)]: connection added (new peer)
INFO: 2024/08/01 05:35:27.296060 Setting up IPsec between fa:e5:26:56:81:20(site1-dra-worker2) and e6:53:1c:64:cf:41(site1-dra-worker1)
DEBU: 2024/08/01 05:35:27.315805 fastdp ->[192.168.31.62:6784|ee:24:a9:e7:50:0e(site1-dra-control0)]: confirmed
DEBU: 2024/08/01 05:35:27.316100 sleeve ->[192.168.31.62:6783|ee:24:a9:e7:50:0e(site1-dra-control0)]: Confirm
DEBU: 2024/08/01 05:35:27.316691 [allocator fa:e5:26:56:81:20]: Allocator.OnGossip: 954 bytes
DEBU: 2024/08/01 05:35:27.316742 sleeve ->[192.168.31.62:6783|ee:24:a9:e7:50:0e(site1-dra-control0)]: confirmed
DEBU: 2024/08/01 05:35:27.316805 sleeve ->[192.168.31.62:6783|ee:24:a9:e7:50:0e(site1-dra-control0)]: sendHeartbeat
INFO: 2024/08/01 05:35:27.316930 ipsec: InitSALocal: 192.168.31.63 -> 192.168.31.67 :6784 0xd5bcdb45
DEBU: 2024/08/01 05:35:27.318068 sleeve ->[192.168.31.62:6783|ee:24:a9:e7:50:0e(site1-dra-control0)]: handleHeartbeat
DEBU: 2024/08/01 05:35:27.332535 fastdp ->[192.168.31.63:6784|76:a6:72:91:2a:47(site1-dra-control1)]: confirmed
INFO: 2024/08/01 05:35:27.332787 ipsec: InitSALocal: 192.168.31.64 -> 192.168.31.67 :6784 0x2f5468b7
DEBU: 2024/08/01 05:35:27.333015 sleeve ->[192.168.31.63:6783|76:a6:72:91:2a:47(site1-dra-control1)]: Confirm
DEBU: 2024/08/01 05:35:27.333265 sleeve ->[192.168.31.63:6783|76:a6:72:91:2a:47(site1-dra-control1)]: confirmed
DEBU: 2024/08/01 05:35:27.333296 sleeve ->[192.168.31.63:6783|76:a6:72:91:2a:47(site1-dra-control1)]: sendHeartbeat
DEBU: 2024/08/01 05:35:27.345639 fastdp ->[192.168.31.64:6784|aa:e0:01:9b:27:4e(site1-dra-director1)]: confirmed
DEBU: 2024/08/01 05:35:27.345774 sleeve ->[192.168.31.64:6783|aa:e0:01:9b:27:4e(site1-dra-director1)]: Confirm
INFO: 2024/08/01 05:35:27.345892 ipsec: InitSALocal: 192.168.31.65 -> 192.168.31.67 :6784 0xa504600c
DEBU: 2024/08/01 05:35:27.345987 sleeve ->[192.168.31.64:6783|aa:e0:01:9b:27:4e(site1-dra-director1)]: confirmed

**Comment by megarajan** [comment]
Any clues / pointers  ?

**Comment by rajch** [comment]
Sorry, day job is keeping me busy. I'll take a look as soon as i can.

**Comment by megarajan** [comment]
hi can you help us proceed forward in debugging this ?

**Comment by rajch** [comment]
Okay, I am back. Looking at your second set of logs, it looks like fastdp connections had restarted at some point. Can you look at recent logs, and search specifically for the following messages:

`got Heartbeat from peer, marking fastdp forwarder as healthy`
or 
`missed Heartbeat from peer, marking fastdp forwarder as un-healthy`

See which one came later, and from what IP. Date/time and IP will be shown earlier in the same log line.

If "marking fastdp forwarder as healthy" came later, you are good. If not, we will have to break and re-establish connections between peers.  But first, tell me what you see in the logs.

**Comment by rajch** [comment]
Also, please upgrade your weave version! I started maintaining this fork because I had problems with 2.8.1.

**Comment by rajch** [comment]
_Please_ upgrade, as soon as possible. Meanwhile, the logs seem to suggest that the fallback to sleeve is because of MTU. The default MTU setting for weave net is 1376, and the underlay should allow for 84-87 bytes of overhear. The logs seem to say that the effective MTU is 1414, so lowering weave net's MTU should solve the problem. Try setting the WEAVE_MTU environment variable to 1324, wherever you are launching weave.

While you are at it, set the environment variable CHECKPOINT_DISABLE to 1, also. Later versions do this automatically. This won't affect your problem, but you will stop seeing `Error checking version:` errors in your logs.

**Comment by megarajan** [comment]
I tested with setting WEAVE_MTU  to 1324 .

 export  WEAVE_MTU=1324
 weave launch --log-level=debug --trusted-subnets 10.32.0.0/12 -H unix:///var/run/weave/weave.sock -H tcp://127.0.0.1:12375 --ipalloc-init --password=cisco123  consensus=3 192.169.67.171
   
But it didnt help and connections came up in sleeve mode only.

Will continue testing  and update.




DEBU: 2024/08/12 18:02:56.049577 fastdp: broadcast{0 true} {8e:bc:56:4f:93:e9 ff:ff:ff:ff:ff:ff}
DEBU: 2024/08/12 18:02:56.329842 sleeve ->[192.169.67.172:6783|e6:7f:3a:29:67:f0(dra1-sys04-control-0)]: handleHeartbeat
DEBU: 2024/08/12 18:02:56.361739 fastdp ->[192.169.67.172:6784|e6:7f:3a:29:67:f0(dra1-sys04-control-0)]: missed Heartbeat from peer, marking fastdp forwarder as un-healthy
DEBU: 2024/08/12 18:02:56.361901 overlay_switch ->[e6:7f:3a:29:67:f0(dra1-sys04-control-0)] Removing fastdp from the list of forwarders
INFO: 2024/08/12 18:02:56.362032 overlay_switch ->[e6:7f:3a:29:67:f0(dra1-sys04-control-0)] using sleeve
DEBU: 2024/08/12 18:02:56.452147 sleeve ->[192.169.67.172:6783|e6:7f:3a:29:67:f0(dra1-sys04-control-0)]: sendHeartbeat
DEBU: 2024/08/12 18:02:56.487989 fastdp ->[192.169.67.172:6784|e6:7f:3a:29:67:f0(dra1-sys04-control-0)]: sending Heartbeat to peer

**Comment by megarajan** [comment]
tested it with changing MTU , but didnt help .

but when we upgraded to the next  version we didnt see the connections moving to sleeve .

**Comment by rajch** [comment]
Thank you. Closing this issue now.
