### ISSUE TITLE
Steps to start weave 2.8.8 as as docker container in ubuntu vm ?

### ISSUE THREAD

**Issue by megarajan** [rajch/weave#12]
I am trying to start weave2.8.8 in my ubuntu vm.

I downloaded the docker images from below links and loaded them in my vm.

docker pull rajchaudhuri/weavedb:2.8.8
docker pull rajchaudhuri/weave

cps@site1-dra-worker2:~$ docker images
REPOSITORY             TAG           IMAGE ID       CREATED         SIZE
15491a6ff7a8           weavedb       15491a6ff7a8   6 weeks ago     267B
0de40054f312           weave-2.8.8   0de40054f312   6 weeks ago     68.2MB

Running weavedb

cps@site1-dra-worker2:~$ sudo docker run 15491a6ff7a8
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "data-only": executable file not found in $PATH: unknown.
ERRO[0003] error waiting for container: context canceled
cps@site1-dra-worker2:~$

Running weave

cps@site1-dra-worker2:~$ sudo docker run 0de40054f312
FATA: 2024/08/02 12:13:29.051225 [boltDB] Unable to open /weavedb/weavedata.db: write /weavedb/weavedata.db: bad file descriptor
cps@site1-dra-worker2:~$

Could you please share the steps to run these images ?

**Comment by rajch** [comment]
You need to use the `weave` script, rather than work with the images yourself. See [here](https://rajch.github.io/weave/install/installing-weave) for how to install it, and [here](https://rajch.github.io/weave/install/using-weave) for how to use it.

**Comment by megarajan** [comment]
ok thanks

**Comment by rajch** [comment]
Closing this issue.
