### ISSUE TITLE
Are the latest versions weave-2.8.8 tested in ubuntu 22.04 ?

### ISSUE THREAD

**Issue by megarajan** [rajch/weave#13]
Hi,

We upgraded to ubuntu 22 and with weave 2.8.1 all connections come up only in sleeve mode .

Is latest version of weave 2.8.8 tested with ubuntu 22.04 ?

thanks
Megarajan

**Comment by rajch** [comment]
No, but it has been tested with Debian 12 'bookworm', which is roughly what Ubuntu 22.04 is based on. Did you try adjusting the MTU like I suggested in the [other issue](https://github.com/rajch/weave/issues/11#issuecomment-2271736665)?

**Comment by megarajan** [comment]
yes, thanks for confirming . I tried adjusting the weave mtu, didnt seem to help, but upgrading to the next version we dont see the same issue. 

We can close this issue.
