### ISSUE TITLE
Is there a way to dump the controlplane topology of a weave cluster ?

### ISSUE THREAD

**Issue by megarajan** [rajch/weave#14]
In our weave cluster, we are using connlimit as 100 and because of that if we reboot a vm we are seeing major disruptions in weave cluster . for example in below image, if we reboot control-0 vm, we see major disruptions in weave cluster.

![image](https://github.com/user-attachments/assets/1c764520-fded-406a-ae2f-3f6c4436c10e)

Is there any way to dump the control plane network topology to check which vms handle most of hte weave traffic or reconstruct it from any data ?

**Comment by rajch** [comment]
You could monitor Weave metrics, via Prometheus. Weave publishes a number of interesting metrics, including number or peer-to-peer connections, number of fastdp flows and number of ip addresses. 

By default, weave listens only on the local interface on each node to publish metrics. You will need to start it using a `--metrics-addr` option to make it listen on a dedicated (or all) IP address and port. See [here](https://rajch.github.io/weave/tasks/manage/metrics#metrics-endpoint-addresses).

That same page will give you the list of available metrics.
