### ISSUE TITLE
v 2.8.8 unable to start weave

### ISSUE THREAD

**Issue by yaronr** [rajch/weave#7]
ExecStartPre=/usr/bin/env curl -L --create-dirs https://reweave.azurewebsites.net/get-weave -o /etc/weave/weave
ExecStartPre=/usr/bin/env chmod a+x /etc/weave/weave
/etc/weave/weave launch

 docker: Error response from daemon: manifest for rajchaudhuri/weaveexec:2.8.8 not found: manifest unknown: manifest unknown.

**Comment by rajch** [comment]
Extremely sorry. One of the steps in the deployment process for v2.8.8 had failed silently, and the rest had gone ahead. The deployment has properly completed now, and weave should work once more.

The process has also been corrected so this problem does not occur again.

**Comment by rajch** [comment]
Closing this.
