### ISSUE TITLE
Does weave have support for multiple control nodes and how can we increase no of control nodes ?

### ISSUE THREAD

**Issue by megarajan** [rajch/weave#8]
hi

does weave have a concept of control nodes ? 
I have checked the docs and I cannot find anything related to control nodes.

But in this page
https://zivukushingai.medium.com/weave-net-troubleshooting-faq-950c3ad89d85

I see the below statement.

If the network topology is large, you can consider increasing the number of Weave Net control nodes to improve performance and stability.

Is the above statement valid and true ? if so how can I increase the number of weavenet control nodes ?

thanks
Megarajan

**Comment by rajch** [comment]
The term "control node" does not appear anywhere in the codebase, either. I don't know where the article author gets it from.

regards
Raj

**Comment by megarajan** [comment]
thanks for your reply.
